server:
  port: 8083

spring:
  application:
    name: ms-pedidos360-notify
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
