server:
  port: 8084

spring:
  application:
    name: ms-pedidos360-audit
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:f280f365-653c-4282-b1ee-200e91b01736}/v2.0
          audiences: ${AZURE_API_CLIENT_ID:08c770a5-21a6-4434-8d59-28723c7c759d}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: pedidos360-audit
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

pedidos360:
  messaging:
    topic-orders-events: orders.events
    topic-audit-timeline: audit.timeline

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:audit;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/${DB_SERVICE:ORCLPDB1}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USER:pedidos360}
    password: ${DB_PASSWORD:changeme}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
