server:
  port: 8081

spring:
  application:
    name: ms-pedidos360-orders

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:CHANGE_ME}/v2.0
          audiences: api://${AZURE_API_CLIENT_ID:CHANGE_ME}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

pedidos360:
  messaging:
    exchange-direct: cmd.direct
    exchange-dlx: cmd.dead.dlx
    topic-orders-events: orders.events
  catalog:
    base-url: ${CATALOG_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/${DB_SERVICE:ORCLPDB1}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USER:pedidos360}
    password: ${DB_PASSWORD:changeme}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
